# Generated by Django 5.1.1 on 2025-04-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
