# Generated by Django 5.1.1 on 2025-04-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_private_key_user_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='USER_1000', max_length=10),
            preserve_default=False,
        ),
    ]
