# Generated by Django 5.1.1 on 2025-04-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='public_key',
        ),
        migrations.AlterField(
            model_name='user',
            name='private_key',
            field=models.CharField(max_length=1280),
        ),
    ]
