# Generated by Django 5.1.1 on 2025-04-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_public_key_alter_user_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private_key',
            field=models.CharField(max_length=2048),
        ),
    ]
