# Generated by Django 5.1.1 on 2025-04-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
    ]
